# Site settings
show_downloads: false
title: Windup Documentation
permalink: pretty
repository: windup/windup-documentation
baseurl: /
url: https://windup.github.io/windup-documentation
repository_url: https://github.com/windup/windup-documentation

type: website
future: false

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

plugins: [jekyll-asciidoc, jekyll-paginate, jekyll-redirect-from, jekyll-feed, jekyll-sitemap, premonition, jekyll/tagging,  jekyll-seo-tag]

# empty array for asciidoc
asciidoc: {}
# upstream doc attributes
asciidoctor:
  attributes:
  - showtitle=@
  - build=upstream
  - imagesdir=../topics/images
  - UserCLIBookName=CLI Guide
  - RulesDevBookName=Rules Development Guide
  - EclipseCrsGuideTitle=Eclipse and Red Hat CodeReady Studio Plugin Guide
  - IntroToMTABookName=Introduction to the Migration Toolkit for Applications
  - WebConsoleBookName=Web Console Guide
  - MavenBookName=Maven Plugin Guide
  safe: unsafe

exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - .history
  - CONTRIBUTING.adoc
  - Gemfile.lock
  - topics/

tag_page_layout: tag
tag_page_dir: /tag/

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
